apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingesta
  namespace: chaniweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingesta
  template:
    metadata:
      labels:
        app: ingesta
    spec:
      containers:
        - name: ingesta
          image: tu-registro.azurecr.io/chaniweb-ingesta:latest
          env:
            - name: REDIS_URL
              value: "redis://redis:6379"
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
